---
title: "Urban-Rural Gap"
author: "Navya Mote"
date: "October 29, 2017"
input: "CSV File"
---
```{r echo=FALSE}
library(tidyverse)
library(lattice)
source('hw.r')
library(gridExtra)

colNames <- function(x){
  colNam = colnames(x)
  colInt = 1:length(colNam)
  names(colInt) = colNam
  return(colInt)
}
```
```{r}
studentUrbanRural <- read.csv(file="GapUrbanRural.csv")
studentUrbanRural
```

```{r echo=TRUE, fig.width=20, fig.height=12}

ggplot(studentUrbanRural,
  aes(x = Overall, y = GapUrbanRural, color=Country,
    descend = TRUE)) +
geom_point(size=5) +
labs(x = "Overall grade 6 completion rate (%)",y = "Percentage point gap between urban and rural",
  title = paste0("b. Urban-rural"),cex.lab=3) + hw + scale_x_continuous(breaks=seq(20,100,10),limits=c(20,100)) +
  scale_y_continuous(breaks=seq(-20,50,10),limits=c(-20,50)) +
  geom_hline(yintercept=0) + 
  geom_segment(aes(x= Overall, xend=Overall, y=0, yend= GapUrbanRural), data=studentUrbanRural)
```

